"""Optional self-hosted AI "live read" companion for the static auction app.

This is a small, dependency-free HTTP server that a self-hoster runs alongside
the static browser app to power its optional #liveread panel. The hosted static
app ships with the AI OFF; pointing the app's config.js AI_ENDPOINT at this
server is what turns the live read on.

All AI content is generated by the operator's OWN Claude access: either the
local `claude` CLI on the machine that runs this server, or the operator's own
Anthropic API key. Nothing here talks to any hosted service on the app's behalf,
and there is no shared key.

Design notes:
  - Stdlib only. No Flask, no requests, no Anthropic SDK. Runs with a bare
    `python3 server.py`.
  - No database. Unlike the personal tool this is ported from, this server holds
    no state about players, valuations, or sales. The browser client already
    computed all of that and POSTs the full context (a plain-text board brief,
    the deterministic Call, and the staged player) on every stage. This server
    only assembles the prompt and relays it to the model.
  - Fire-and-forget. POST /api/stage returns a sequence number immediately and
    does the model call on a background thread. The browser polls GET
    /api/copilot until the matching sequence is ready. A newer stage invalidates
    an older in-flight read.

Endpoints:
  POST /api/stage    kick off a live read (see the contract in README.md)
  GET  /api/copilot  poll the current read: {seq, status, text, player}
  GET  /             tiny health check
  OPTIONS *          CORS preflight

Environment:
  PORT               listen port (default 8017)
  ALLOW_ORIGIN       CORS Access-Control-Allow-Origin (default *)
  COPILOT_MODEL      model id (default claude-opus-4-8)
  COPILOT_EFFORT     effort level for the CLI transport (default medium)
  COPILOT_TRANSPORT  "cli" (default) or "api"
  ANTHROPIC_API_KEY  required for the api transport / CLI-missing fallback
"""
import json
import os
import re
import shutil
import subprocess
import threading
import urllib.request
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

# Config from the environment. Read once at import; a restart picks up changes.
PORT = int(os.environ.get("PORT", "8017"))
ALLOW_ORIGIN = os.environ.get("ALLOW_ORIGIN", "*")
MODEL = os.environ.get("COPILOT_MODEL", "claude-opus-4-8")
EFFORT = os.environ.get("COPILOT_EFFORT", "medium")
TRANSPORT = os.environ.get("COPILOT_TRANSPORT", "cli").lower()
DEFAULT_MODE = "synthesize"

# Current live read. GET /api/copilot returns this dict verbatim.
COPILOT = {"seq": 0, "status": "idle", "text": "", "player": None}


def condense_read(text):
    """Hard guard on the live read: the contract is one action line. If the
    model rambles anyway (old habits, prompt drift), strip bullet formatting
    and keep only the trailing sentences - the action is always last."""
    t = " ".join(seg.strip().lstrip("-").strip()
                 for seg in text.splitlines() if seg.strip())
    if len(t) <= 280:
        return t
    parts = re.split(r"(?<=[.!?;]) +", t)
    keep = []
    for s in reversed(parts):
        if keep and sum(len(x) for x in keep) + len(s) > 220:
            break
        keep.insert(0, s)
    return " ".join(keep)


def call_block(call):
    """Render the client's deterministic Call (verdict pill, worth, plan cap,
    room-bids estimate, slot envelopes, reasons) as a compact text block so
    the model refines the frame I am already reading instead of inventing a
    second one. Empty dict = older client; the block just says so."""
    if not call:
        return "THE CALL ON MY SCREEN: (not supplied)"
    lines = [f"THE CALL ON MY SCREEN: {call.get('verdict', '?')}; "
             f"worth ${call.get('worth', '?')}"
             + (f"; my plan cap ~${call['plan_cap']}"
                if call.get('plan_cap') is not None
                and call.get('worth') is not None
                and call['plan_cap'] < call['worth'] else "")
             + (f"; room bids ~${call['room_bids']}"
                if call.get('room_bids') is not None else "")]
    slots = call.get("slots") or []
    if slots:
        lines.append("  open slots he could fill (my plan $): "
                     + ", ".join(f"{s['slot']} ~${s['plan']}" for s in slots))
    elif call.get("bench_open"):
        lines.append(f"  bench only: ~${call.get('bench_per', 1)} across "
                     f"{call['bench_open']} spot(s)")
    for r in call.get("reasons") or []:
        lines.append(f"  - {r}")
    if call.get("tags"):
        lines.append("  tags: " + ", ".join(call["tags"]))
    return "\n".join(lines)


# Two read modes. Both get THE CALL so they speak in its frame.
# synthesize: the read is the single verdict, rolling the Call's markers and
#   the live ledger into one bid instruction. Default.
# complement: the Call stays the verdict; the read adds only what the Call
#   cannot know, or goes blank. (Kept for A/B in mocks.)
PROMPT_SYNTHESIZE = (
    "JOB: ONE final instruction for this auction. Weigh THE CALL's markers "
    "(worth = break-even value; plan cap = my envelope for the slot he "
    "fills; room bids = the expected price; comparable supply) TOGETHER with "
    "what only the live ledger tells you (which owners can actually reach the "
    "price and still need the position, flow, inflation, my remaining plan, "
    "the market opinion if given). DO THE MATH INTERNALLY, never show it. "
    "DECISION RULE: my default stop is the LOWER of worth and plan cap. "
    "Go above plan cap only when the ledger says he is worth squeezing my "
    "other slots for (thin supply, rivals who cannot reach him, a plan that "
    "can absorb it), and then the instruction must name it: 'Take him to "
    "$12, over the $5 plan.' Never name a price above my max bid. "
    "OUTPUT FORMAT, strict: first sentence = the instruction with my stop "
    "price, imperative ('Bid to $5, stop.' / 'Let him go.' / 'Take him to "
    "$12, over the $5 plan.'). Second sentence = the ONE reason that decides "
    "it, at most 12 words, preferring what the ledger adds (a rival's money, "
    "flow, my plan) over a bullet the Call already lists. Name a rival only "
    "if the LEDGER's needs column shows he still needs this position and his "
    "maxbid reaches the price; when unsure, say 'the funded rivals' instead. "
    "15-25 words total, no bullets, no preamble, no "
    "hedging, no restating the Call's numbers except the one you depart from.")
PROMPT_COMPLEMENT = (
    "JOB: THE CALL is the verdict I am already acting on; do NOT repeat or "
    "rephrase anything it shows (worth, plan cap, room bids, comparable "
    "supply). Add ONLY what it cannot know from the live ledger: which rival "
    "owners can realistically reach the price and still need this position, "
    "flow or inflation shifts, a tighter winning-price forecast, or a reason "
    "to depart from the Call's ceiling. DO THE MATH INTERNALLY. Name a rival "
    "only if the LEDGER's needs column shows he still needs this position and "
    "his maxbid reaches the price. OUTPUT: one "
    "short sentence, max 20 words, framed as an adjustment to the Call "
    "('stop at $14, not $16: ...' or 'hold at worth: ...'), no bullets, no "
    "preamble. If the ledger adds nothing the Call does not already say, "
    "output exactly: no read.")

ROSTER_FIT_RULE = (
    " ROSTER-FIT RULE, overrides everything: obey the MY ROSTER FIT line. "
    "'fills my OPEN slot' = normal read. 'FLX candidate ONLY at a clear "
    "discount' = instruct a buy only if the stop price is at least 25% under "
    "worth; otherwise 'Let him go.' 'BENCH ONLY' or 'ALL skill starters "
    "FILLED' = never instruct a buy at starter money; the only allowed buy "
    "instruction starts with 'Bench value:' and stops at $3 or less; default "
    "to 'Let him go.'")

# The frame every read is handed before the brief and staged player. Ported
# verbatim from the personal tool; contains no personal data.
PREAMBLE = (
    "You are the live auction co-pilot for the team marked ME>. Below is the "
    "full draft state (pure-consensus values, no personal adjustments), then "
    "the player being auctioned right now, then THE CALL: the deterministic "
    "verdict card already on my screen. Vocabulary: an owner's remaining "
    "money is his BANK; 'purse' means only MY planned hold for K+DEF+bench "
    "and never describes another owner.")


def _num(v):
    """Coerce a JSON value to float for formatting, or None if it is not a
    number. The client may send ints, floats, numeric strings, or nulls."""
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def build_prompt(body):
    """Assemble preamble + client brief + staged-player context + the mode
    prompt + roster-fit rule. All context comes from the POST body; there is
    no database read. Mirrors the personal tool's post_stage assembly."""
    player = body.get("player") or {}
    name = player.get("name") or "?"
    mode = body.get("mode") or DEFAULT_MODE
    call = body.get("call") or {}
    brief = body.get("brief") or ""
    fit = (body.get("roster_fit") or "").strip()

    ctx = f"STAGED FOR AUCTION RIGHT NOW: {name}"
    if player.get("pos"):
        ctx += f" ({player['pos']})"
    bits = []
    ov = _num(player.get("our_value"))
    if ov is not None:
        bits.append(f"our value ${ov:.0f}")
    pp = _num(player.get("proj_pts"))
    if pp is not None:
        bits.append(f"projected {pp:.0f} pts")
    eb = _num(player.get("est_bid"))
    if eb is not None:
        bits.append(f"est. league bid ${eb:.0f}")
    if bits:
        ctx += ", " + ", ".join(bits)
    if fit:
        ctx += "\n" + fit
    ctx += "\n" + call_block(call)

    prompt = (
        PREAMBLE + "\n\n" + brief + "\n" + ctx + "\n\n"
        + (PROMPT_COMPLEMENT if mode == "complement" else PROMPT_SYNTHESIZE)
        + ROSTER_FIT_RULE)
    return name, prompt


def _call_cli(prompt, claude_bin):
    """Default transport: shell out to the local `claude` CLI, headless. The
    co-pilot uses NO tools, so an empty MCP config keeps cold starts fast and
    predictable instead of loading every user-level MCP server."""
    try:
        r = subprocess.run(
            [claude_bin, "-p", prompt,
             "--model", MODEL,
             "--effort", EFFORT,
             "--strict-mcp-config", "--mcp-config", '{"mcpServers":{}}'],
            capture_output=True, text=True, timeout=180)
        return (r.stdout or "").strip() or ("error: " + (r.stderr or "")[:300])
    except Exception as e:
        return f"co-pilot error: {e}"


def _call_api(prompt, api_key):
    """Alternative transport: the Anthropic Messages API over HTTPS using only
    urllib, so no SDK install is needed. Uses the operator's own key."""
    payload = json.dumps({
        "model": MODEL,
        "max_tokens": 400,
        "messages": [{"role": "user", "content": prompt}],
    }).encode()
    req = urllib.request.Request(
        "https://api.anthropic.com/v1/messages",
        data=payload,
        headers={
            "x-api-key": api_key,
            "anthropic-version": "2023-06-01",
            "content-type": "application/json",
        },
        method="POST")
    try:
        with urllib.request.urlopen(req, timeout=180) as resp:
            data = json.loads(resp.read().decode())
        content = data.get("content") or []
        if content and isinstance(content[0], dict):
            return (content[0].get("text") or "").strip()
        return "co-pilot error: empty response from the API"
    except Exception as e:
        return f"co-pilot error: {e}"


def run_ai(prompt):
    """Pick a transport and return the model's text, or a clear error string.
    Default is the local CLI. If COPILOT_TRANSPORT=api and a key is set, use
    the HTTPS API. If the CLI is missing, fall through to the API when a key
    is set; otherwise return a plain error the read panel can show."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if TRANSPORT == "api":
        if api_key:
            return _call_api(prompt, api_key)
        return ("co-pilot error: COPILOT_TRANSPORT=api but ANTHROPIC_API_KEY "
                "is not set")
    claude_bin = shutil.which("claude")
    if claude_bin:
        return _call_cli(prompt, claude_bin)
    if api_key:
        return _call_api(prompt, api_key)
    return ("co-pilot error: claude CLI not found on PATH and "
            "ANTHROPIC_API_KEY is not set")


def post_stage(body):
    """Fire the co-pilot: build the prompt from the POSTed context and hand it
    to the model asynchronously. Returns immediately; the room never blocks.
    A newer stage bumps the seq and invalidates this one's late result."""
    name, prompt = build_prompt(body)
    COPILOT["seq"] += 1
    myseq = COPILOT["seq"]
    COPILOT.update(status="thinking", text="", player=name)

    def work():
        out = run_ai(prompt)
        if not out.startswith(("error:", "co-pilot")):
            out = condense_read(out)
        # Only the newest stage may publish its result.
        if COPILOT["seq"] == myseq:
            COPILOT.update(status="ready", text=out)

    threading.Thread(target=work, daemon=True).start()
    return {"ok": True, "seq": myseq}


class Handler(BaseHTTPRequestHandler):
    def _cors(self):
        self.send_header("Access-Control-Allow-Origin", ALLOW_ORIGIN)
        self.send_header("Access-Control-Allow-Methods", "GET, POST, OPTIONS")
        self.send_header("Access-Control-Allow-Headers", "Content-Type")
        self.send_header("Access-Control-Max-Age", "86400")

    def _send(self, code, body, ctype="application/json"):
        data = body if isinstance(body, bytes) else json.dumps(body).encode()
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Cache-Control", "no-store")
        self.send_header("Content-Length", str(len(data)))
        self._cors()
        self.end_headers()
        self.wfile.write(data)

    def do_OPTIONS(self):
        self.send_response(204)
        self._cors()
        self.send_header("Content-Length", "0")
        self.end_headers()

    def do_GET(self):
        try:
            if self.path == "/api/copilot":
                self._send(200, COPILOT)
            elif self.path in ("/", "/health"):
                self._send(200, {"ok": True, "service": "copilot-server",
                                 "transport": TRANSPORT, "model": MODEL})
            else:
                self._send(404, {"error": "not found"})
        except Exception as e:
            import traceback
            traceback.print_exc()
            self._send(500, {"error": f"server error: {e}"})

    def do_POST(self):
        try:
            length = int(self.headers.get("Content-Length", 0))
            body = json.loads(self.rfile.read(length) or b"{}")
            if self.path == "/api/stage":
                res = post_stage(body)
            else:
                res = {"error": "not found"}
            self._send(200 if res.get("ok") else 400, res)
        except Exception as e:
            import traceback
            traceback.print_exc()
            self._send(500, {"error": f"server error: {e}"})

    def log_message(self, fmt, *args):
        pass


def main():
    httpd = ThreadingHTTPServer(("127.0.0.1", PORT), Handler)
    key_set = bool(os.environ.get("ANTHROPIC_API_KEY"))
    cli = shutil.which("claude")
    print(f"copilot-server on http://localhost:{PORT}")
    print(f"  transport={TRANSPORT}  model={MODEL}  effort={EFFORT}")
    print(f"  claude CLI on PATH: {'yes' if cli else 'no'}  "
          f"ANTHROPIC_API_KEY set: {'yes' if key_set else 'no'}")
    print(f"  CORS Access-Control-Allow-Origin: {ALLOW_ORIGIN}")
    if TRANSPORT == "api" and not key_set:
        print("  WARNING: COPILOT_TRANSPORT=api but ANTHROPIC_API_KEY is unset; "
              "reads will return an error until you set it.")
    elif TRANSPORT != "api" and not cli and not key_set:
        print("  WARNING: no claude CLI and no ANTHROPIC_API_KEY; reads will "
              "return an error. Install the claude CLI or set a key.")
    httpd.serve_forever()


if __name__ == "__main__":
    main()
