/* GENERATED by scripts/generate_money_talks_config.mjs from the real
 * Sleeper API -- do not hand-edit. Re-run the script if Money_Talks'
 * scoring/roster settings change. See sleeper.md for why this is a
 * generated static file rather than a live client-side fetch. */

export const MONEY_TALKS_LEAGUE = {
  name: "Money Talks",
  platform: "sleeper",
  season: "2026",
  teams: 12,
  budget: 200,
  weeks: 17,
  roster_slots: {"QB":1,"RB":2,"WR":2,"TE":1,"FLEX":1,"SUPER_FLEX":1,"IDP_FLEX":2},
  full_roster: {"QB":1,"RB":2,"WR":2,"TE":1,"FLEX":1,"SUPER_FLEX":1,"IDP_FLEX":2,"BN":8},
  scoring: {
    "pass": {
      "yd": 0.04,
      "td": 4,
      "int": -1
    },
    "rush": {
      "yd": 0.1,
      "td": 6
    },
    "rec": {
      "yd": 0.1,
      "td": 6,
      "ppr_by_pos": {
        "QB": 1,
        "RB": 1,
        "WR": 1,
        "TE": 1
      }
    },
    "misc": {
      "fumble_lost": -2,
      "two_pt": 2
    },
    "idp": {
      "tkl_solo": 1.5,
      "tkl_ast": 1,
      "tkl_loss": 1,
      "sack": 3,
      "qb_hit": 1,
      "int": 5,
      "int_ret_yd": 0.1,
      "ff": 3,
      "fum_rec": 2,
      "fum_ret_yd": 0.1,
      "pass_def": 2,
      "blk_kick": 2,
      "safe": 2,
      "def_td": 6
    }
  },
  model_params: {
    baseline_bench_share: 0.15,
    vols_blend_alpha: 0,
    tier_gap_theta: 0.2,
    dollar_slots_per_team: 18,
    /* Evaluated two approaches for this league (see docs/FIXES_LOG.md,
     * 2026-09-02) and blended them: measured history used where it
     * exists (offense baselines below, from FantasyEngine's real 2023-
     * 2025 Money_Talks draft/spend data, config/vorp_baselines.R), the
     * general engine formula kept as fallback elsewhere. */
    measured_baselines: { QB: 32, RB: 39, WR: 54, TE: 15 },
    idp_pricing: { slots_per_team: 2, top_value: 3, rest_value: 1 },
  },
  team_names: ["LaPorta Potty","Back Akers","Pacheckin her out","lukelangan","Jettin' Magic","Blood, Sweat and Beers","Game of Mahomes","Peekegbuka","Lights Out","Skol","Gibb Me My Money","MoNami21"],
  me: 1,
  sleeper_league_id: "1389342583871766528",
  sleeper_draft_id: "1389342583871766529",
  sleeper_user_id: "462234296409649152",
};
