#!/usr/bin/env node
/* Generates app/player_history.js: for every player ever drafted in
 * Money_Talks, what price he went for each season and whether that season
 * was a keeper price. Baked in at build time like money_talks_config.js --
 * this is historical/immutable data (past seasons never change), so there
 * is no reason to hit the network for it during a live draft.
 *
 * Walks the real league's own previous_league_id chain (verified live
 * 2026-09-04: 1389342583871766528 (2026) -> 1255739715391324161 (2025) ->
 * 1080548975884816384 (2024) -> 979603195267702784 (2023) ->
 * 842910536927686656 (2022) -> 717428145615089664 (2021) -> null) rather
 * than hardcoding season league_ids, so a future re-run picks up
 * additional prior seasons automatically if the chain ever extends.
 *
 * Usage: node scripts/generate_player_history.mjs
 */

const CURRENT_LEAGUE_ID = "1389342583871766528";

async function main() {
  const history = {}; // player_id -> [{year, price, keeper}], chronological

  let leagueId = CURRENT_LEAGUE_ID;
  const seasons = [];
  /* Walk back from the CURRENT league's own previous_league_id, i.e. skip
   * the current (not-yet-drafted-for-real, or in-progress) season itself --
   * this file is about COMPLETED prior seasons only. */
  const current = await fetch(`https://api.sleeper.app/v1/league/${leagueId}`).then((r) => r.json());
  leagueId = current.previous_league_id;

  while (leagueId) {
    const league = await fetch(`https://api.sleeper.app/v1/league/${leagueId}`).then((r) => r.json());
    seasons.push({ season: league.season, draftId: league.draft_id });
    leagueId = league.previous_league_id;
  }

  for (const { season, draftId } of seasons) {
    if (!draftId) continue;
    const picks = await fetch(`https://api.sleeper.app/v1/draft/${draftId}/picks`).then((r) => r.json());
    for (const p of picks) {
      if (!p.player_id || p.metadata?.amount == null) continue;
      const price = Number(p.metadata.amount);
      if (!Number.isFinite(price)) continue;
      (history[p.player_id] ||= []).push({
        year: Number(season), price, keeper: !!p.is_keeper,
      });
    }
  }

  // chronological within each player, oldest first
  for (const rows of Object.values(history)) rows.sort((a, b) => a.year - b.year);

  const sortedKeys = Object.keys(history).sort((a, b) => Number(a) - Number(b));
  const sortedHistory = {};
  for (const k of sortedKeys) sortedHistory[k] = history[k];

  const out = `/* GENERATED by scripts/generate_player_history.mjs from the real
 * Sleeper API -- do not hand-edit. Historical/immutable (past seasons
 * never change), so this is baked in rather than fetched live. Re-run if
 * the league's previous_league_id chain ever extends further back.
 * Seasons covered: ${seasons.map((s) => s.season).join(", ")}.
 * Keyed by raw Sleeper player_id (no "sl:" prefix) -- see app.js's
 * historyFor() for the lookup. */

export const PLAYER_HISTORY = ${JSON.stringify(sortedHistory)};
`;

  const fs = await import("node:fs");
  fs.writeFileSync(new URL("../app/player_history.js", import.meta.url), out);
  console.log(`Wrote app/player_history.js -- ${sortedKeys.length} players, seasons ${seasons.map((s) => s.season).join("/")}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
