#!/usr/bin/env node
/* Generates app/actual_stats.js: real per-season stat totals (2021-2025)
 * for the same critical scoring categories the app already tracks for
 * projections (see app.js's STAT_ORDER/STAT_LABELS and sleeper.js's
 * STAT_MAP/IDP_STAT_MAP, which this script mirrors exactly so the
 * projections table and the actuals table speak the same schema).
 *
 * Source: Sleeper's own `/v1/stats/nfl/regular/<season>` -- the same
 * provider already trusted everywhere else in this app, Sleeper-ID-
 * native (no crosswalk/join risk, unlike the FantasyEngine projection
 * join), and verified live 2026-09-04 to use the identical theirs-side
 * key names sleeper.js's STAT_MAP/IDP_STAT_MAP already expect (pass_yd,
 * rush_td, rec, idp_tkl_solo, etc.) -- projections and actuals share one
 * raw stat vocabulary on Sleeper's side, not two to maintain.
 *
 * Historical/immutable (a completed season never changes), so baked in
 * at build time like player_history.js and money_talks_config.js, not
 * fetched live during the draft.
 *
 * Usage: node scripts/generate_actual_stats.mjs
 */

const SEASONS = [2021, 2022, 2023, 2024, 2025];

// Mirrors sleeper.js's STAT_MAP/IDP_STAT_MAP exactly -- same schema, same names.
const STAT_MAP = {
  pass_yd: "pass_yds", pass_td: "pass_tds", pass_int: "ints",
  pass_cmp: "completions", pass_att: "pass_atts",
  rush_yd: "rush_yds", rush_td: "rush_tds", rush_att: "rush_atts",
  rec: "receptions", rec_yd: "rec_yds", rec_td: "rec_tds",
  fum_lost: "fumbles_lost",
};
const IDP_STAT_MAP = {
  idp_tkl_solo: "tkl_solo", idp_tkl_ast: "tkl_ast", idp_sack: "sacks",
  idp_int: "def_ints", idp_ff: "forced_fumbles", idp_fum_rec: "fum_rec",
  idp_blk_kick: "blocked_kicks", idp_safe: "safeties",
};

async function main() {
  const out = {}; // sleeper player_id -> { year -> { ourStatKey: value } }

  for (const season of SEASONS) {
    console.log(`Fetching ${season} regular-season stat totals...`);
    const resp = await fetch(`https://api.sleeper.app/v1/stats/nfl/regular/${season}`);
    if (!resp.ok) throw new Error(`${season} fetch failed: ${resp.status}`);
    const raw = await resp.json();
    let kept = 0;

    for (const [pid, stats] of Object.entries(raw)) {
      const line = {};
      for (const [theirs, ours] of Object.entries(STAT_MAP)) {
        if (stats[theirs] != null) line[ours] = stats[theirs];
      }
      for (const [theirs, ours] of Object.entries(IDP_STAT_MAP)) {
        if (stats[theirs] != null) line[ours] = stats[theirs];
      }
      const twoPt = (stats.pass_2pt ?? 0) + (stats.rush_2pt ?? 0) + (stats.rec_2pt ?? 0);
      if (twoPt) line.two_pt = twoPt;
      if (Object.keys(line).length === 0) continue; // no relevant stat this season -- skip

      (out[pid] ||= {})[season] = line;
      kept++;
    }
    console.log(`  ${kept} players with a relevant stat line`);
  }

  const sortedKeys = Object.keys(out).sort((a, b) => Number(a) - Number(b));
  const sorted = {};
  for (const k of sortedKeys) sorted[k] = out[k];

  const outFile = `/* GENERATED by scripts/generate_actual_stats.mjs from the real Sleeper
 * API -- do not hand-edit. Real per-season stat totals, ${SEASONS[0]}-${SEASONS[SEASONS.length - 1]},
 * for the critical scoring categories (mirrors sleeper.js's STAT_MAP/
 * IDP_STAT_MAP exactly). Historical/immutable, so baked in rather than
 * fetched live. Keyed by raw Sleeper player_id (no "sl:" prefix), then
 * by season year. Re-run to extend once a new season completes. */

export const ACTUAL_STATS = ${JSON.stringify(sorted)};
`;

  const fs = await import("node:fs");
  fs.writeFileSync(new URL("../app/actual_stats.js", import.meta.url), outFile);
  console.log(`Wrote app/actual_stats.js -- ${sortedKeys.length} players total`);
}

main().catch((e) => { console.error(e); process.exit(1); });
