#!/usr/bin/env node
/* Generates app/money_talks_config.js from the real Sleeper API. Run this
 * whenever Money_Talks' real scoring/roster settings change (they
 * shouldn't between now and the real draft, but re-run if in doubt --
 * see sleeper.md for why this is a generated static file, not a live
 * client-side fetch: this is a one-and-done deployment for one league
 * whose settings are already known, so baking them in avoids a runtime
 * dependency and a CORS surface for no real benefit on draft night.
 *
 * Usage: node scripts/generate_money_talks_config.mjs
 */

const LEAGUE_ID = "1389342583871766528";

const IDP_SCORING_KEY_MAP = {
  // engine's scoring.idp key -> Sleeper's scoring_settings key
  tkl_solo: "idp_tkl_solo", tkl_ast: "idp_tkl_ast", tkl_loss: "idp_tkl_loss",
  sack: "idp_sack", qb_hit: "idp_qb_hit", int: "idp_int",
  int_ret_yd: "idp_int_ret_yd", ff: "idp_ff", fum_rec: "idp_fum_rec",
  fum_ret_yd: "idp_fum_ret_yd", pass_def: "idp_pass_def",
  blk_kick: "idp_blk_kick", safe: "idp_safe", def_td: "idp_def_td",
};

/* Sleeper stores scoring weights as float32, so 0.04 round-trips as
 * 0.03999999910593033 etc. -- round to 4 decimals (well past any real
 * scoring granularity used in practice) rather than writing the noise
 * into a checked-in file. */
const r = (x) => Math.round(x * 10000) / 10000;

async function main() {
  const league = await fetch(`https://api.sleeper.app/v1/league/${LEAGUE_ID}`)
    .then((r) => r.json());
  const [rosters, users] = await Promise.all([
    fetch(`https://api.sleeper.app/v1/league/${LEAGUE_ID}/rosters`).then((r) => r.json()),
    fetch(`https://api.sleeper.app/v1/league/${LEAGUE_ID}/users`).then((r) => r.json()),
  ]);
  const userById = Object.fromEntries(users.map((u) => [u.user_id, u]));
  /* team_names ordered by roster_id (1..teams) -- app.js's owner code
   * assumes team_names.length === league.teams; leaving this short (e.g.
   * empty) leaves some owner slots undefined, which crashes downstream
   * code that reads a roster shape off each owner (caught 2026-09-02
   * running the quick-start flow for real in a browser -- see
   * docs/FIXES_LOG.md). Collin's own team ("mondo_duke") is flagged as
   * `me` by its position in this array. */
  const rostersByOwner = rosters.sort((a, b) => a.roster_id - b.roster_id);
  const teamNames = rostersByOwner.map((r) => {
    const u = userById[r.owner_id];
    return (u?.metadata?.team_name) || u?.display_name || `Team ${r.roster_id}`;
  });
  /* League-scoped user objects (GET .../users) don't carry a `username`
   * field, only `display_name` -- verified directly against a live pull
   * (2026-09-02) rather than assumed from the top-level /v1/user/{username}
   * shape, which does have one. */
  const meIndex = rostersByOwner.findIndex((r) => userById[r.owner_id]?.display_name === "mondo_duke");
  const s = league.scoring_settings;

  /* The engine's stat-line schema (app/sleeper.js's fetchSleeper) sums
   * pass_2pt + rush_2pt + rec_2pt into a single `two_pt` count, so
   * scoring.misc.two_pt must be one flat per-conversion value -- only
   * correct if Sleeper's 3 separate 2pt weights actually agree. Assert
   * that rather than silently picking one and hoping, so a future
   * scoring-settings change that splits them can't ship unnoticed. */
  if (s.pass_2pt !== s.rush_2pt || s.pass_2pt !== s.rec_2pt) {
    throw new Error(
      `pass_2pt (${s.pass_2pt}), rush_2pt (${s.rush_2pt}), and rec_2pt ` +
      `(${s.rec_2pt}) no longer agree -- the engine's single two_pt stat ` +
      `can't represent 3 different weights. Needs a real fix (either a ` +
      `per-type 2pt stat in the engine, or an explicit call on how to ` +
      `combine them), not a silent pick of one value.`);
  }

  const scoring = {
    pass: { yd: r(s.pass_yd), td: r(s.pass_td), int: r(s.pass_int) },
    rush: { yd: r(s.rush_yd), td: r(s.rush_td) },
    rec: {
      yd: r(s.rec_yd), td: r(s.rec_td),
      ppr_by_pos: { QB: r(s.rec ?? 0), RB: r(s.rec ?? 0), WR: r(s.rec ?? 0), TE: r(s.rec ?? 0) },
    },
    misc: { fumble_lost: r(s.fum_lost), two_pt: r(s.pass_2pt) },
    idp: Object.fromEntries(
      Object.entries(IDP_SCORING_KEY_MAP).map(([ours, theirs]) => [ours, r(s[theirs] ?? 0)])),
  };

  const rosterSlots = { QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, SUPER_FLEX: 1, IDP_FLEX: 2 };
  const fullRoster = { ...rosterSlots, BN: 8 };

  const out = `/* GENERATED by scripts/generate_money_talks_config.mjs from the real
 * Sleeper API -- do not hand-edit. Re-run the script if Money_Talks'
 * scoring/roster settings change. See sleeper.md for why this is a
 * generated static file rather than a live client-side fetch. */

export const MONEY_TALKS_LEAGUE = {
  name: "Money Talks",
  platform: "sleeper",
  season: "2026",
  teams: ${league.settings.num_teams},
  budget: 200,
  weeks: 17,
  roster_slots: ${JSON.stringify(rosterSlots)},
  full_roster: ${JSON.stringify(fullRoster)},
  scoring: ${JSON.stringify(scoring, null, 2).split("\n").join("\n  ")},
  model_params: {
    baseline_bench_share: 0.15,
    vols_blend_alpha: 0,
    tier_gap_theta: 0.2,
    dollar_slots_per_team: 18,
    /* Evaluated two approaches for this league (see docs/FIXES_LOG.md,
     * 2026-09-02) and blended them: measured history used where it
     * exists (offense baselines below, from FantasyEngine's real 2023-
     * 2025 Money_Talks draft/spend data, config/vorp_baselines.R), the
     * general engine formula kept as fallback elsewhere. */
    measured_baselines: { QB: 32, RB: 39, WR: 54, TE: 15 },
    idp_pricing: { slots_per_team: 2, top_value: 3, rest_value: 1 },
  },
  team_names: ${JSON.stringify(teamNames)},
  me: ${meIndex},
  sleeper_league_id: "${LEAGUE_ID}",
};
`;

  const fs = await import("node:fs");
  fs.writeFileSync(new URL("../app/money_talks_config.js", import.meta.url), out);
  console.log("Wrote app/money_talks_config.js");
}

main().catch((e) => { console.error(e); process.exit(1); });
